harmony_visualizer_main_homepage:
    pattern:  /
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:index }

start_survey:
    pattern:  /start
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:startSurvey }

HarmonyVisualizerMainBundle_form:
    resource: "@HarmonyVisualizerMainBundle/Resources/config/routing/form.yml"
    prefix:   /form

cordova_plugin_contacts:
    pattern:  /cordova-plugin-contacts
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:visuContacts }

cordova_plugin_file_transfer:
    pattern:  /cordova-plugin-file-transfer
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:visuFileTransfer }


matrix_cordova_plugin_contacts:
    pattern:  /matrix-cordova-plugin-contacts
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:matrixContacts }

matrix_cordova_plugin_file_transfer:
    pattern:  /matrix-cordova-plugin-file-transfer
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:matrixFileTransfer }

form:
    pattern:  /form
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:form }

formComplete:
    pattern:  /formComplete
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:formComplete }


# Survey routes

survey_visu_cordova_plugin_contacts:
    pattern:  /survey-cordova-plugin-contacts
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:visuContactsForm }

survey_visu_cordova_plugin_file_transfer:
    pattern:  /survey-cordova-plugin-file-transfer
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:visuFileTransferForm }

survey_matrix_cordova_plugin_contacts:
    pattern:  /survey-matrix-cordova-plugin-contacts
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:matrixContactsForm }

survey_matrix_cordova_plugin_file_transfer:
    pattern:  /survey-matrix-cordova-plugin-file-transfer
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:matrixFileTransferForm }
