harmony_visualizer_main_homepage:
    pattern:  /
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:index }

HarmonyVisualizerMainBundle_form:
    resource: "@HarmonyVisualizerMainBundle/Resources/config/routing/form.yml"
    prefix:   /form

visu_cordova_plugin_contacts:
    pattern:  /visu1
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:visuContact }

visu_cordova_plugin_file_transfert:
    pattern:  /visu2
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:visuFileTransfer }

form:
    pattern:  /form
    defaults: { _controller: HarmonyVisualizerMainBundle:Default:form }

