parameters:
#    harmony_visualizer_main.example.class: HarmonyVisualizer\MainBundle\Example

services:
#    harmony_visualizer_main.example:
#        class: %harmony_visualizer_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
