form:
    pattern:  /
    defaults: { _controller: "HarmonyVisualizerMainBundle:Form:index" }

form_show:
    pattern:  /{id}/show
    defaults: { _controller: "HarmonyVisualizerMainBundle:Form:show" }

form_new:
    pattern:  /new
    defaults: { _controller: "HarmonyVisualizerMainBundle:Form:new" }

form_create:
    pattern:  /create
    defaults: { _controller: "HarmonyVisualizerMainBundle:Form:create" }
    requirements: { _method: post }

form_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HarmonyVisualizerMainBundle:Form:edit" }

form_update:
    pattern:  /{id}/update
    defaults: { _controller: "HarmonyVisualizerMainBundle:Form:update" }
    requirements: { _method: post|put }

form_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HarmonyVisualizerMainBundle:Form:delete" }
    requirements: { _method: post|delete }
