var mapping={
	"D1":"Alpha",
	"D2":"Bravo",
	"D3":"Charlie",
	"D4":"Delta",
	"D5":"Echo",
	"D6":"Foxtrot",
	"D7":"Golf",
	"D8":"Hotel",
	"D9":"India",

	"M1":"com.app.generic",
	"M2":"com.app.io",
	"M3":"com.app.lib",
	"M4":"com.app.model",
	"M5":"com.app.stats",
	"M6":"com.app.test",
	"M7":"com.app.trace",
	"M8":"com.app.util",

	"D":"Developpers",
	"M":"Modules",
	"PC":"Commits (%)",
	"DAF":"DAF",
	"MAF":"MAF",
	"NBI":"Items",
	"NBC":"Contributions",
	"TPC":"Total commits (%)",
}
