var mapping = {
"M1":"/",
"M2":"data",
"M3":"source/app",
"M4":"source/data",
"M5":"source/model",
"M6":"source/model/src",
"M7":"source/out",
"M8":"source/test",
"M9":"source/test/src",
"M10":"src",
"D1":"basicDM",
"D2":"borbag",
"D3":"Borbag",
"D4":"elyas-bhy",
"D5":"Hélène",
"D6":"Largaroth",
"D7":"Ryan Herbert",
"D":"Developpers",
"M":"Modules",
"PC":"Commits (%)",
"DAF":"DAF",
"MAF":"MAF",
"NBI":"Items",
"NBC":"Contributions",
"TPC":"Total commits (%)"
}