var mapping = {
"D1":"Andrew Grieve",
"D2":"Anis Kadri",
"D3":"Archana Naik",
"D4":"Benn Mapes",
"D5":"Bryan Higgins",
"D6":"David Kemp",
"D7":"Gao Chun",
"D8":"Hardeep Shoker",
"D9":"Herm Wong",
"D10":"Ian Clelland",
"D11":"James Jong",
"D12":"Jeffrey Heifetz",
"D13":"Jesse MacFadyen",
"D14":"Joe Bowser",
"D15":"Kristoffer Flores",
"D16":"lmnbeyond",
"D17":"lorinbeer",
"D18":"Max Woghiren",
"D19":"Maxim Ermilov",
"D20":"Piotr Zalewa",
"D21":"purplecabbage",
"D22":"sgrebnov",
"D23":"Shazron Abdullah",
"D24":"Steven Gill",
"D25":"Tim Kim",
"M1":"/",
"M2":"doc",
"M3":"docs",
"M4":"docs/Contact",
"M5":"docs/ContactAddress",
"M6":"docs/ContactError",
"M7":"docs/ContactField",
"M8":"docs/ContactFindOptions",
"M9":"docs/ContactName",
"M10":"docs/ContactOrganization",
"M11":"docs/parameters",
"M12":"src/android",
"M13":"src/blackberry10",
"M14":"src/firefoxos",
"M15":"src/ios",
"M16":"src/ubuntu",
"M17":"src/wp",
"M18":"src/wp7",
"M19":"src/wp8",
"M20":"test",
"M21":"test/autotest",
"M22":"test/autotest/html",
"M23":"test/autotest/pages",
"M24":"test/autotest/tests",
"M25":"test/contacts",
"M26":"www",
"M27":"www/ios",
"D":"Developpers",
"M":"Modules",
"PC":"Commits (%)",
"DAF":"DAF",
"MAF":"MAF",
"NBI":"Items",
"NBC":"Contributions",
"TPC":"Total commits (%)"
}