var mapping = {
"D1":"Andrew Grieve",
"D2":"Anis Kadri",
"D3":"Archana Naik",
"D4":"Benn Mapes",
"D5":"Bryan Higgins",
"D6":"Colin Mahoney",
"D7":"Fil Maj",
"D8":"Hardeep Shoker",
"D9":"Hasan Ahmad",
"D10":"hermwong",
"D11":"Ian Clelland",
"D12":"Jesse MacFadyen",
"D13":"Joe Bowser",
"D14":"Max Woghiren",
"D15":"Maxim Ermilov",
"D16":"Maxime LUCE",
"D17":"purplecabbage",
"D18":"Shazron Abdullah",
"D19":"Steven Gill",
"D20":"Tim Kim",
"D21":"Viras-",
"M1":"/",
"M2":"doc",
"M3":"docs/filetransfer",
"M4":"docs/filetransfererror",
"M5":"src/amazon",
"M6":"src/android",
"M7":"src/ios",
"M8":"src/ubuntu",
"M9":"src/wp",
"M10":"src/wp7",
"M11":"src/wp8",
"M12":"test",
"M13":"test/autotest",
"M14":"test/autotest/html",
"M15":"test/autotest/pages",
"M16":"test/autotest/tests",
"M17":"www",
"M18":"www/blackberry10",
"M19":"www/windows8",
"M20":"www/wp",
"M21":"www/wp7",
"D":"Developpers",
"M":"Modules",
"PC":"Commits (%)",
"DAF":"DAF",
"MAF":"MAF",
"NBI":"Items",
"NBC":"Contributions",
"TPC":"Total commits (%)"
}